services:
  wallpaper-webview:
    image: wallpaper-webview
    build: ./app/
    container_name: wallpaper-webview
    restart: always
    ports:
      - "3090:3090"
    volumes:
      # 脚本目录
      - ./app:/app
      # Steam 账号的登录凭证
      - ./Steam:/root/Steam
      # 下载位置
      - /downloads:/app/downloads
    environment:
      # 代理
      - HTTP_PROXY=
      - HTTPS_PROXY=
