services:
  wallpaper-engine-download-web:
    image: wallpaper-engine-download-web
    build: .
    container_name: wallpaper-engine-download-web
    restart: always
    ports:
      - "3090:3090"
    volumes:
      # 下载位置
      - ./downloads:/app/downloads

      # Steam部分
      # SteamCMD 脚本目录
      - ./steamcmd:/app/steamcmd
      # Steam 账号的登录凭证
      - ./Steam:/root/Steam
    environment:
      # 端口
      - PORT=3090
      # 商店地区代码
      # - STEAM_COUNTRY=HK
      # Steam 账号和密码 (首次需要手机验证)
      # - STEAM_USERNAME=
      # - STEAM_PASSWORD=
      # 代理
      # - HTTP_PROXY=
      # - HTTPS_PROXY=
